#!/usr/bin/env php

<?php
$phake_file = 'PhakeFile';

if(!file_exists($phake_file)){
    echo "PhakeFile not found! \n";
    exit();
}

$function_name = isset($argv[1]) ? $argv[1] : '_default';

require_once($phake_file);
$args = "";
if(count($argv) > 2) { //arguments
	for ($i=2; $i < count($argv); $i++) { 
		$args .= "'".$argv[$i]."'";
		if($i != count($argv) - 1)
			$args .= ",";
	}
}

$action = $function_name . "(".$args.");";
//echo $action; echo "\n"; exit();

if(function_exists($function_name))
    eval($action);
else
    echo "task not found: '$function_name' \n";

?>